#!/bin/bash

######################################################
#                       train                        #
######################################################

# python3 main_train_model_tgn.py --dataset_path="a_dataset/tfData/hexa_magneto/TGN/case1"  \
# --error_model="torque" --log_dir="hexa_magneto/TGN/case1_edge64_np5" --save_model_path="/saved_model" \
# --learning_rate=1e-3 --batch_size=64 --epoch_size=400 --num_processing_steps=5 --edge_latent_size=64 --edge_output_size=1

# python3 main_train_model_tgn.py --dataset_path="a_dataset/tfData/hexa_magneto/TGN/case2"  \
# --error_model="torque" --log_dir="hexa_magneto/TGN/case2_edge64_np5" --save_model_path="/saved_model" \
# --learning_rate=1e-3 --batch_size=64 --epoch_size=400 --num_processing_steps=5 --edge_latent_size=64 --edge_output_size=1

# python3 main_train_model_tgn.py --dataset_path="a_dataset/tfData/hexa_magneto/TGN/case3"  \
# --error_model="torque" --log_dir="hexa_magneto/TGN/case3_edge64_np5" --save_model_path="/saved_model" \
# --learning_rate=1e-3 --batch_size=64 --epoch_size=400 --num_processing_steps=5 --edge_latent_size=64 --edge_output_size=1

# python3 main_train_model_tgn.py --dataset_path="a_dataset/tfData/hexa_magneto/TGN/case4"  \
# --error_model="torque" --log_dir="hexa_magneto/TGN/case4_edge64_np5" --save_model_path="/saved_model" \
# --learning_rate=1e-3 --batch_size=64 --epoch_size=400 --num_processing_steps=5 --edge_latent_size=64 --edge_output_size=1

# python3 main_train_model_tgn.py --dataset_path="a_dataset/tfData/hexa_magneto/TGN/case5"  \
# --error_model="torque" --log_dir="hexa_magneto/TGN/case5_edge64_np5" --save_model_path="/saved_model" \
# --learning_rate=1e-3 --batch_size=64 --epoch_size=400 --num_processing_steps=5 --edge_latent_size=64 --edge_output_size=1

python3 main_train_model_tgn.py --dataset_path="a_dataset/tfData/hexa_magneto/TGN/case5_2"  \
--error_model="torque" --log_dir="hexa_magneto/TGN/case5_2_edge64_np5" --save_model_path="/saved_model" \
--learning_rate=1e-3 --batch_size=64 --epoch_size=400 --num_processing_steps=5 --edge_latent_size=64 --edge_output_size=1

python3 main_train_model_tgn.py --dataset_path="a_dataset/tfData/hexa_magneto/TGN/case5_3"  \
--error_model="torque" --log_dir="hexa_magneto/TGN/case5_3_edge64_np5" --save_model_path="/saved_model" \
--learning_rate=1e-3 --batch_size=64 --epoch_size=400 --num_processing_steps=5 --edge_latent_size=64 --edge_output_size=1

# python3 main_train_model_tgn.py --dataset_path="a_dataset/tfData/hexa_magneto/TGN/case6"  \
# --error_model="torque" --log_dir="hexa_magneto/TGN/case6_edge64_np5" --save_model_path="/saved_model" \
# --learning_rate=1e-3 --batch_size=64 --epoch_size=400 --num_processing_steps=5 --edge_latent_size=64 --edge_output_size=1

# python3 main_train_model_tgn.py --dataset_path="a_dataset/tfData/hexa_magneto/TGN/case7"  \
# --error_model="torque" --log_dir="hexa_magneto/TGN/case7_edge64_np5" --save_model_path="/saved_model" \
# --learning_rate=1e-3 --batch_size=64 --epoch_size=400 --num_processing_steps=5 --edge_latent_size=64 --edge_output_size=1

# python3 main_train_model_tgn.py --dataset_path="a_dataset/tfData/hexa_magneto/TGN/case8"  \
# --error_model="torque" --log_dir="hexa_magneto/TGN/case8_edge64_np5" --save_model_path="/saved_model" \
# --learning_rate=1e-3 --batch_size=64 --epoch_size=400 --num_processing_steps=5 --edge_latent_size=64 --edge_output_size=1

# python3 main_train_model_tgn.py --dataset_path="a_dataset/tfData/hexa_magneto/TGN/case9"  \
# --error_model="torque" --log_dir="hexa_magneto/TGN/case9_edge64_np5" --save_model_path="/saved_model" \
# --learning_rate=1e-3 --batch_size=64 --epoch_size=400 --num_processing_steps=5 --edge_latent_size=64 --edge_output_size=1

# python3 main_train_model_tgn.py --dataset_path="a_dataset/tfData/hexa_magneto/TGN/case10"  \
# --error_model="torque" --log_dir="hexa_magneto/TGN/case10_edge64_np5" --save_model_path="/saved_model" \
# --learning_rate=1e-3 --batch_size=64 --epoch_size=400 --num_processing_steps=5 --edge_latent_size=64 --edge_output_size=1

# python3 main_train_model_tgn.py --dataset_path="a_dataset/tfData/hexa_magneto/TGN/case11"  \
# --error_model="torque" --log_dir="hexa_magneto/TGN/case11_edge64_np5" --save_model_path="/saved_model" \
# --learning_rate=1e-3 --batch_size=64 --epoch_size=400 --num_processing_steps=5 --edge_latent_size=64 --edge_output_size=1

# python3 main_train_model_tgn.py --dataset_path="a_dataset/tfData/hexa_magneto/TGN/case12"  \
# --error_model="torque" --log_dir="hexa_magneto/TGN/case12_edge64_np5" --save_model_path="/saved_model" \
# --learning_rate=1e-3 --batch_size=64 --epoch_size=400 --num_processing_steps=5 --edge_latent_size=64 --edge_output_size=1

# python3 main_train_model_tgn.py --dataset_path="a_dataset/tfData/hexa_magneto/TGN/case13"  \
# --error_model="torque" --log_dir="hexa_magneto/TGN/case13_edge64_np5" --save_model_path="/saved_model" \
# --learning_rate=1e-3 --batch_size=64 --epoch_size=400 --num_processing_steps=5 --edge_latent_size=64 --edge_output_size=1

# python3 main_train_model_tgn.py --dataset_path="a_dataset/tfData/hexa_magneto/TGN/caseall"  \
# --error_model="torque" --log_dir="hexa_magneto/TGN/caseall_edge64_np5" --save_model_path="/saved_model" \
# --learning_rate=1e-3 --batch_size=64 --epoch_size=400 --num_processing_steps=5 --edge_latent_size=64 --edge_output_size=1


######################################################
#                       validation                   #
######################################################

#0 - test
# python3 main_check_model_tgn.py \
# --batch_size=64 \
# --dataset_path="a_dataset/tfData/hexa_magneto/TGN/case1"  \
# --test_dataset_path="a_dataset/tfData/hexa_magneto/TGN/case1" \
# --load_model_path="a_result/hexa_magneto/TGN/case1_edge64_np5/saved_model" \
# --log_dir="check_model/hexa_magneto/TGN/case1_test1_edge64_np5" \
# --num_processing_steps=5 \
# --edge_latent_size=64 \
# --edge_output_size=1


# 1
# python3 main_check_model_tgn.py \
# --batch_size=64 \
# --dataset_path="a_dataset/tfData/hexa_magneto/TGN/case1"  \
# --test_dataset_path="a_dataset/tfData/hexa_magneto/TGN/case2" \
# --load_model_path="a_result/hexa_magneto/TGN/case1_edge64_np5/saved_model" \
# --log_dir="check_model/hexa_magneto/TGN/case1_test2_edge64_np5" \
# --num_processing_steps=5 \
# --edge_latent_size=64 \
# --edge_output_size=1

# #2
# python3 main_check_model_tgn.py \
# --batch_size=64 \
# --dataset_path="a_dataset/tfData/hexa_magneto/TGN/case1"  \
# --test_dataset_path="a_dataset/tfData/hexa_magneto/TGN/case3" \
# --load_model_path="a_result/hexa_magneto/TGN/case1_edge64_np5/saved_model" \
# --log_dir="check_model/hexa_magneto/TGN/case1_test3_edge64_np5" \
# --num_processing_steps=5 \
# --edge_latent_size=64 \
# --edge_output_size=1

# #3
# python3 main_check_model_tgn.py \
# --batch_size=64 \
# --dataset_path="a_dataset/tfData/hexa_magneto/TGN/case5"  \
# --test_dataset_path="a_dataset/tfData/hexa_magneto/TGN/case4" \
# --load_model_path="a_result/hexa_magneto/TGN/case5_edge64_np5/saved_model" \
# --log_dir="check_model/hexa_magneto/TGN/case5_test4_edge64_np5" \
# --num_processing_steps=5 \
# --edge_latent_size=64 \
# --edge_output_size=1

#3
python3 main_check_model_tgn.py \
--batch_size=64 \
--dataset_path="a_dataset/tfData/hexa_magneto/TGN/case5_2"  \
--test_dataset_path="a_dataset/tfData/hexa_magneto/TGN/case4" \
--load_model_path="a_result/hexa_magneto/TGN/case5_2_edge64_np5/saved_model" \
--log_dir="check_model/hexa_magneto/TGN/case5_2_test4_edge64_np5" \
--num_processing_steps=5 \
--edge_latent_size=64 \
--edge_output_size=1

#3
python3 main_check_model_tgn.py \
--batch_size=64 \
--dataset_path="a_dataset/tfData/hexa_magneto/TGN/case5_3"  \
--test_dataset_path="a_dataset/tfData/hexa_magneto/TGN/case4" \
--load_model_path="a_result/hexa_magneto/TGN/case5_3_edge64_np5/saved_model" \
--log_dir="check_model/hexa_magneto/TGN/case5_3_test4_edge64_np5" \
--num_processing_steps=5 \
--edge_latent_size=64 \
--edge_output_size=1

# #4
# python3 main_check_model_tgn.py \
# --batch_size=64 \
# --dataset_path="a_dataset/tfData/hexa_magneto/TGN/case6"  \
# --test_dataset_path="a_dataset/tfData/hexa_magneto/TGN/case4" \
# --load_model_path="a_result/hexa_magneto/TGN/case6_edge64_np5/saved_model" \
# --log_dir="check_model/hexa_magneto/TGN/case6_test4_edge64_np5" \
# --num_processing_steps=5 \
# --edge_latent_size=64 \
# --edge_output_size=1

# #5
# python3 main_check_model_tgn.py \
# --batch_size=64 \
# --dataset_path="a_dataset/tfData/hexa_magneto/TGN/case7"  \
# --test_dataset_path="a_dataset/tfData/hexa_magneto/TGN/case10" \
# --load_model_path="a_result/hexa_magneto/TGN/case7_edge64_np5/saved_model" \
# --log_dir="check_model/hexa_magneto/TGN/case7_test10_edge64_np5" \
# --num_processing_steps=5 \
# --edge_latent_size=64 \
# --edge_output_size=1

# #6
# python3 main_check_model_tgn.py \
# --batch_size=64 \
# --dataset_path="a_dataset/tfData/hexa_magneto/TGN/case8"  \
# --test_dataset_path="a_dataset/tfData/hexa_magneto/TGN/case10" \
# --load_model_path="a_result/hexa_magneto/TGN/case8_edge64_np5/saved_model" \
# --log_dir="check_model/hexa_magneto/TGN/case8_test10_edge64_np5" \
# --num_processing_steps=5 \
# --edge_latent_size=64 \
# --edge_output_size=1

# #7
# python3 main_check_model_tgn.py \
# --batch_size=64 \
# --dataset_path="a_dataset/tfData/hexa_magneto/TGN/case9"  \
# --test_dataset_path="a_dataset/tfData/hexa_magneto/TGN/case10" \
# --load_model_path="a_result/hexa_magneto/TGN/case9_edge64_np5/saved_model" \
# --log_dir="check_model/hexa_magneto/TGN/case9_test10_edge64_np5" \
# --num_processing_steps=5 \
# --edge_latent_size=64 \
# --edge_output_size=1

## 8
# python3 main_check_model_tgn.py \
# --batch_size=64 \
# --dataset_path="a_dataset/tfData/hexa_magneto/TGN/case11"  \
# --test_dataset_path="a_dataset/tfData/hexa_magneto/TGN/case13" \
# --load_model_path="a_result/hexa_magneto/TGN/case11_edge64_np5/saved_model" \
# --log_dir="check_model/hexa_magneto/TGN/case11_test13_edge64_np5" \
# --num_processing_steps=5 \
# --edge_latent_size=64 \
# --edge_output_size=1

# #9
# python3 main_check_model_tgn.py \
# --batch_size=64 \
# --dataset_path="a_dataset/tfData/hexa_magneto/TGN/case12"  \
# --test_dataset_path="a_dataset/tfData/hexa_magneto/TGN/case13" \
# --load_model_path="a_result/hexa_magneto/TGN/case12_edge64_np5/saved_model" \
# --log_dir="check_model/hexa_magneto/TGN/case12_test13_edge64_np5" \
# --num_processing_steps=5 \
# --edge_latent_size=64 \
# --edge_output_size=1

# #10
# python3 main_check_model_tgn.py \
# --batch_size=64 \
# --dataset_path="a_dataset/tfData/hexa_magneto/TGN/case13"  \
# --test_dataset_path="a_dataset/tfData/hexa_magneto/TGN/caseall" \
# --load_model_path="a_result/hexa_magneto/TGN/case13_edge64_np5/saved_model" \
# --log_dir="check_model/hexa_magneto/TGN/case13_testall_edge64_np5" \
# --num_processing_steps=5 \
# --edge_latent_size=64 \
# --edge_output_size=1
