#!/bin/bash

######################################################
#                       train                        #
######################################################

# python3 main_train_model_ffnn.py --dataset_path="a_dataset/tfData/hexa_magneto/FFNN/case1"  \
# --error_model="torque" --log_dir="hexa_magneto/FFNN/case1_latent256_layer3" --save_model_path="/saved_model" \
# --learning_rate=1e-3 --batch_size=64 --epoch_size=300 --latent_size=256 --output_size=18 --num_layer=3

# python3 main_train_model_ffnn.py --dataset_path="a_dataset/tfData/hexa_magneto/FFNN/case2"  \
# --error_model="torque" --log_dir="hexa_magneto/FFNN/case2_latent256_layer3" --save_model_path="/saved_model" \
# --learning_rate=1e-3 --batch_size=64 --epoch_size=300 --latent_size=256 --output_size=18 --num_layer=3

# python3 main_train_model_ffnn.py --dataset_path="a_dataset/tfData/hexa_magneto/FFNN/case3"  \
# --error_model="torque" --log_dir="hexa_magneto/FFNN/case3_latent256_layer3" --save_model_path="/saved_model" \
# --learning_rate=1e-3 --batch_size=64 --epoch_size=300 --latent_size=256 --output_size=18 --num_layer=3

# python3 main_train_model_ffnn.py --dataset_path="a_dataset/tfData/hexa_magneto/FFNN/case4"  \
# --error_model="torque" --log_dir="hexa_magneto/FFNN/case4_latent256_layer3" --save_model_path="/saved_model" \
# --learning_rate=1e-3 --batch_size=64 --epoch_size=300 --latent_size=256 --output_size=18 --num_layer=3

# python3 main_train_model_ffnn.py --dataset_path="a_dataset/tfData/hexa_magneto/FFNN/case5"  \
# --error_model="torque" --log_dir="hexa_magneto/FFNN/case5_latent256_layer3" --save_model_path="/saved_model" \
# --learning_rate=1e-3 --batch_size=64 --epoch_size=300 --latent_size=256 --output_size=18 --num_layer=3

# python3 main_train_model_ffnn.py --dataset_path="a_dataset/tfData/hexa_magneto/FFNN/case6"  \
# --error_model="torque" --log_dir="hexa_magneto/FFNN/case6_latent256_layer3" --save_model_path="/saved_model" \
# --learning_rate=1e-3 --batch_size=64 --epoch_size=300 --latent_size=256 --output_size=18 --num_layer=3

# python3 main_train_model_ffnn.py --dataset_path="a_dataset/tfData/hexa_magneto/FFNN/case7"  \
# --error_model="torque" --log_dir="hexa_magneto/FFNN/case7_latent256_layer3" --save_model_path="/saved_model" \
# --learning_rate=1e-3 --batch_size=64 --epoch_size=300 --latent_size=256 --output_size=18 --num_layer=3

# python3 main_train_model_ffnn.py --dataset_path="a_dataset/tfData/hexa_magneto/FFNN/case8"  \
# --error_model="torque" --log_dir="hexa_magneto/FFNN/case8_latent256_layer3" --save_model_path="/saved_model" \
# --learning_rate=1e-3 --batch_size=64 --epoch_size=300 --latent_size=256 --output_size=18 --num_layer=3

# python3 main_train_model_ffnn.py --dataset_path="a_dataset/tfData/hexa_magneto/FFNN/case9"  \
# --error_model="torque" --log_dir="hexa_magneto/FFNN/case9_latent256_layer3" --save_model_path="/saved_model" \
# --learning_rate=1e-3 --batch_size=64 --epoch_size=300 --latent_size=256 --output_size=18 --num_layer=3

# python3 main_train_model_ffnn.py --dataset_path="a_dataset/tfData/hexa_magneto/FFNN/case10"  \
# --error_model="torque" --log_dir="hexa_magneto/FFNN/case10_latent256_layer3" --save_model_path="/saved_model" \
# --learning_rate=1e-3 --batch_size=64 --epoch_size=300 --latent_size=256 --output_size=18 --num_layer=3

# python3 main_train_model_ffnn.py --dataset_path="a_dataset/tfData/hexa_magneto/FFNN/case11"  \
# --error_model="torque" --log_dir="hexa_magneto/FFNN/case11_latent256_layer3" --save_model_path="/saved_model" \
# --learning_rate=1e-3 --batch_size=64 --epoch_size=300 --latent_size=256 --output_size=18 --num_layer=3

# python3 main_train_model_ffnn.py --dataset_path="a_dataset/tfData/hexa_magneto/FFNN/case12"  \
# --error_model="torque" --log_dir="hexa_magneto/FFNN/case12_latent256_layer3" --save_model_path="/saved_model" \
# --learning_rate=1e-3 --batch_size=64 --epoch_size=300 --latent_size=256 --output_size=18 --num_layer=3

# python3 main_train_model_ffnn.py --dataset_path="a_dataset/tfData/hexa_magneto/FFNN/case13"  \
# --error_model="torque" --log_dir="hexa_magneto/FFNN/case13_latent256_layer3" --save_model_path="/saved_model" \
# --learning_rate=1e-3 --batch_size=64 --epoch_size=300 --latent_size=256 --output_size=18 --num_layer=3

# python3 main_train_model_ffnn.py --dataset_path="a_dataset/tfData/hexa_magneto/FFNN/caseall"  \
# --error_model="torque" --log_dir="hexa_magneto/FFNN/caseall_latent256_layer3" --save_model_path="/saved_model" \
# --learning_rate=1e-3 --batch_size=64 --epoch_size=300 --latent_size=256 --output_size=18 --num_layer=3


######################################################
#                       validation                   #
######################################################

#0
# python3 main_check_model_ffnn.py \
# --batch_size=64 \
# --dataset_path="a_dataset/tfData/hexa_magneto/FFNN/case1"  \
# --test_dataset_path="a_dataset/tfData/hexa_magneto/FFNN/case1" \
# --load_model_path="a_result/hexa_magneto/FFNN/case1_latent256_layer3/saved_model" \
# --log_dir="check_model/hexa_magneto/FFNN/case1_test1_latent256_layer3" \
# --latent_size=256 \
# --output_size=18 \
# --num_layer=3

# #1
# python3 main_check_model_ffnn.py \
# --batch_size=64 \
# --dataset_path="a_dataset/tfData/hexa_magneto/FFNN/case1"  \
# --test_dataset_path="a_dataset/tfData/hexa_magneto/FFNN/case2" \
# --load_model_path="a_result/hexa_magneto/FFNN/case1_latent256_layer3/saved_model" \
# --log_dir="check_model/hexa_magneto/FFNN/case1_test2_latent256_layer3" \
# --latent_size=256 \
# --output_size=18 \
# --num_layer=3

# #2
# python3 main_check_model_ffnn.py \
# --batch_size=64 \
# --dataset_path="a_dataset/tfData/hexa_magneto/FFNN/case1"  \
# --test_dataset_path="a_dataset/tfData/hexa_magneto/FFNN/case3" \
# --load_model_path="a_result/hexa_magneto/FFNN/case1_latent256_layer3/saved_model" \
# --log_dir="check_model/hexa_magneto/FFNN/case1_test3_latent256_layer3" \
# --latent_size=256 \
# --output_size=18 \
# --num_layer=3

#3
# python3 main_check_model_ffnn.py \
# --batch_size=64 \
# --dataset_path="a_dataset/tfData/hexa_magneto/FFNN/case5"  \
# --test_dataset_path="a_dataset/tfData/hexa_magneto/FFNN/case4" \
# --load_model_path="a_result/hexa_magneto/FFNN/case5_latent256_layer3/saved_model" \
# --log_dir="check_model/hexa_magneto/FFNN/case5_test4_latent256_layer3" \
# --latent_size=256 \
# --output_size=18 \
# --num_layer=3

# #4
# python3 main_check_model_ffnn.py \
# --batch_size=64 \
# --dataset_path="a_dataset/tfData/hexa_magneto/FFNN/case6"  \
# --test_dataset_path="a_dataset/tfData/hexa_magneto/FFNN/case4" \
# --load_model_path="a_result/hexa_magneto/FFNN/case6_latent256_layer3/saved_model" \
# --log_dir="check_model/hexa_magneto/FFNN/case6_test4_latent256_layer3" \
# --latent_size=256 \
# --output_size=18 \
# --num_layer=3

# #5
# python3 main_check_model_ffnn.py \
# --batch_size=64 \
# --dataset_path="a_dataset/tfData/hexa_magneto/FFNN/case7"  \
# --test_dataset_path="a_dataset/tfData/hexa_magneto/FFNN/case10" \
# --load_model_path="a_result/hexa_magneto/FFNN/case7_latent256_layer3/saved_model" \
# --log_dir="check_model/hexa_magneto/FFNN/case7_test10_latent256_layer3" \
# --latent_size=256 \
# --output_size=18 \
# --num_layer=3

# #6
# python3 main_check_model_ffnn.py \
# --batch_size=64 \
# --dataset_path="a_dataset/tfData/hexa_magneto/FFNN/case8"  \
# --test_dataset_path="a_dataset/tfData/hexa_magneto/FFNN/case10" \
# --load_model_path="a_result/hexa_magneto/FFNN/case8_latent256_layer3/saved_model" \
# --log_dir="check_model/hexa_magneto/FFNN/case8_test10_latent256_layer3" \
# --latent_size=256 \
# --output_size=18 \
# --num_layer=3

# #7
# python3 main_check_model_ffnn.py \
# --batch_size=64 \
# --dataset_path="a_dataset/tfData/hexa_magneto/FFNN/case9"  \
# --test_dataset_path="a_dataset/tfData/hexa_magneto/FFNN/case10" \
# --load_model_path="a_result/hexa_magneto/FFNN/case9_latent256_layer3/saved_model" \
# --log_dir="check_model/hexa_magneto/FFNN/case9_test10_latent256_layer3" \
# --latent_size=256 \
# --output_size=18 \
# --num_layer=3

# #8
# python3 main_check_model_ffnn.py \
# --batch_size=64 \
# --dataset_path="a_dataset/tfData/hexa_magneto/FFNN/case11"  \
# --test_dataset_path="a_dataset/tfData/hexa_magneto/FFNN/case13" \
# --load_model_path="a_result/hexa_magneto/FFNN/case11_latent256_layer3/saved_model" \
# --log_dir="check_model/hexa_magneto/FFNN/case11_test13_latent256_layer3" \
# --latent_size=256 \
# --output_size=18 \
# --num_layer=3

# #9
# python3 main_check_model_ffnn.py \
# --batch_size=64 \
# --dataset_path="a_dataset/tfData/hexa_magneto/FFNN/case12"  \
# --test_dataset_path="a_dataset/tfData/hexa_magneto/FFNN/case13" \
# --load_model_path="a_result/hexa_magneto/FFNN/case12_latent256_layer3/saved_model" \
# --log_dir="check_model/hexa_magneto/FFNN/case12_test13_latent256_layer3" \
# --latent_size=256 \
# --output_size=18 \
# --num_layer=3

# #9
# python3 main_check_model_ffnn.py \
# --batch_size=64 \
# --dataset_path="a_dataset/tfData/hexa_magneto/FFNN/case13"  \
# --test_dataset_path="a_dataset/tfData/hexa_magneto/FFNN/caseall" \
# --load_model_path="a_result/hexa_magneto/FFNN/case13_latent256_layer3/saved_model" \
# --log_dir="check_model/hexa_magneto/FFNN/case13_testall_latent256_layer3" \
# --latent_size=256 \
# --output_size=18 \
# --num_layer=3