#!/bin/bash

## SN

######################################################
#                       dataset                      #
######################################################

# python3 sn_inverse_dynamics/nonamagneto/main_sn_make_dataset.py --raw_data_dir="/a_dataset/rawData/nona_magneto/case1"  \
# --dataset_dir="/a_dataset/tfData/nona_magneto/SN/case1" 

# python3 sn_inverse_dynamics/nonamagneto/main_sn_make_dataset.py --raw_data_dir="/a_dataset/rawData/nona_magneto/case2"  \
# --dataset_dir="/a_dataset/tfData/nona_magneto/SN/case2" 

# python3 sn_inverse_dynamics/nonamagneto/main_sn_make_dataset.py --raw_data_dir="/a_dataset/rawData/nona_magneto/case3"  \
# --dataset_dir="/a_dataset/tfData/nona_magneto/SN/case3" 

# python3 sn_inverse_dynamics/nonamagneto/main_sn_make_dataset.py --raw_data_dir="/a_dataset/rawData/nona_magneto/caseall"  \
# --dataset_dir="/a_dataset/tfData/nona_magneto/SN/caseall" 

######################################################
#                       train                        #
######################################################

# python3 main_train_model_sn.py --dataset_path="a_dataset/tfData/nona_magneto/SN/case1"  \
# --error_model="torque" --log_dir="nona_magneto/SN/case1_latent128_layer2_np2" --save_model_path="/saved_model" \
# --learning_rate=5e-4 --batch_size=64 --epoch_size=300 --latent_size=128 --output_size=3 --num_layer=2 --num_processing_steps=2

# python3 main_train_model_sn.py --dataset_path="a_dataset/tfData/nona_magneto/SN/case2"  \
# --error_model="torque" --log_dir="nona_magneto/SN/case2_latent128_layer2_np2" --save_model_path="/saved_model" \
# --learning_rate=5e-4 --batch_size=64 --epoch_size=300 --latent_size=128 --output_size=3 --num_layer=2 --num_processing_steps=2


# python3 main_train_model_sn.py --dataset_path="a_dataset/tfData/nona_magneto/SN/case3"  \
# --error_model="torque" --log_dir="nona_magneto/SN/case3_latent128_layer2_np2" --save_model_path="/saved_model" \
# --learning_rate=5e-4 --batch_size=64 --epoch_size=300 --latent_size=128 --output_size=3 --num_layer=2 --num_processing_steps=2



######################################################
#                       validation                   #
######################################################

# python3 main_check_model_sn.py \
# --batch_size=64 \
# --dataset_path="a_dataset/tfData/nona_magneto/SN/case1"  \
# --test_dataset_path="a_dataset/tfData/nona_magneto/SN/caseall" \
# --load_model_path="a_result/nona_magneto/SN/case1_latent128_layer2_np2/saved_model" \
# --log_dir="check_model/nona_magneto/SN/case1_caseall_latent128_layer2_np2" \
# --latent_size=128 \
# --output_size=3 \
# --num_layer=2 \
# --num_processing_steps=2

# python3 main_check_model_sn.py \
# --batch_size=64 \
# --dataset_path="a_dataset/tfData/nona_magneto/SN/case2"  \
# --test_dataset_path="a_dataset/tfData/nona_magneto/SN/caseall" \
# --load_model_path="a_result/nona_magneto/SN/case2_latent128_layer2_np2/saved_model" \
# --log_dir="check_model/nona_magneto/SN/case2_caseall_latent128_layer2_np2" \
# --latent_size=128 \
# --output_size=3 \
# --num_layer=2 \
# --num_processing_steps=2

# python3 main_check_model_sn.py \
# --batch_size=64 \
# --dataset_path="a_dataset/tfData/nona_magneto/SN/case3"  \
# --test_dataset_path="a_dataset/tfData/nona_magneto/SN/caseall" \
# --load_model_path="a_result/nona_magneto/SN/case3_latent128_layer2_np2/saved_model" \
# --log_dir="check_model/nona_magneto/SN/case3_caseall_latent128_layer2_np2" \
# --latent_size=128 \
# --output_size=3 \
# --num_layer=2 \
# --num_processing_steps=2


## FFNN

######################################################
#                       dataset                      #
######################################################

python3 ffnn_inverse_dynamics/nonamagneto/main_ffnn_make_dataset.py \
--raw_data_dir="/a_dataset/rawData/nona_magneto/case1"  \
--dataset_dir="/a_dataset/tfData/nona_magneto/FFNN/case1" 

python3 ffnn_inverse_dynamics/nonamagneto/main_ffnn_make_dataset.py \
--raw_data_dir="/a_dataset/rawData/nona_magneto/case2"  \
--dataset_dir="/a_dataset/tfData/nona_magneto/FFNN/case2" 

python3 ffnn_inverse_dynamics/nonamagneto/main_ffnn_make_dataset.py \
--raw_data_dir="/a_dataset/rawData/nona_magneto/case3"  \
--dataset_dir="/a_dataset/tfData/nona_magneto/FFNN/case3" 

python3 ffnn_inverse_dynamics/nonamagneto/main_ffnn_make_dataset.py \
--raw_data_dir="/a_dataset/rawData/nona_magneto/caseall"  \
--dataset_dir="/a_dataset/tfData/nona_magneto/FFNN/caseall" 

######################################################
#                       train                        #
######################################################

python3 main_train_model_ffnn.py --dataset_path="a_dataset/tfData/nona_magneto/FFNN/case1"  \
--error_model="torque" --log_dir="nona_magneto/FFNN/case1_latent256_layer3" --save_model_path="/saved_model" \
--learning_rate=1e-3 --batch_size=64 --epoch_size=300 --latent_size=256 --output_size=27 --num_layer=3

python3 main_train_model_ffnn.py --dataset_path="a_dataset/tfData/nona_magneto/FFNN/case2"  \
--error_model="torque" --log_dir="nona_magneto/FFNN/case2_latent256_layer3" --save_model_path="/saved_model" \
--learning_rate=1e-3 --batch_size=64 --epoch_size=300 --latent_size=256 --output_size=27 --num_layer=3

python3 main_train_model_ffnn.py --dataset_path="a_dataset/tfData/nona_magneto/FFNN/case3"  \
--error_model="torque" --log_dir="nona_magneto/FFNN/case3_latent256_layer3" --save_model_path="/saved_model" \
--learning_rate=1e-3 --batch_size=64 --epoch_size=300 --latent_size=256 --output_size=27 --num_layer=3

######################################################
#                       validation                   #
######################################################

python3 main_check_model_ffnn.py \
--batch_size=64 \
--dataset_path="a_dataset/tfData/nona_magneto/FFNN/case1"  \
--test_dataset_path="a_dataset/tfData/nona_magneto/FFNN/caseall" \
--load_model_path="a_result/nona_magneto/FFNN/case1_latent256_layer3/saved_model" \
--log_dir="check_model/nona_magneto/FFNN/case1_caseall_latent256_layer3" \
--latent_size=256 \
--output_size=27 \
--num_layer=3

python3 main_check_model_ffnn.py \
--batch_size=64 \
--dataset_path="a_dataset/tfData/nona_magneto/FFNN/case2"  \
--test_dataset_path="a_dataset/tfData/nona_magneto/FFNN/caseall" \
--load_model_path="a_result/nona_magneto/FFNN/case2_latent256_layer3/saved_model" \
--log_dir="check_model/nona_magneto/FFNN/case2_caseall_latent256_layer3" \
--latent_size=256 \
--output_size=27 \
--num_layer=3


python3 main_check_model_ffnn.py \
--batch_size=64 \
--dataset_path="a_dataset/tfData/nona_magneto/FFNN/case3"  \
--test_dataset_path="a_dataset/tfData/nona_magneto/FFNN/caseall" \
--load_model_path="a_result/nona_magneto/FFNN/case3_latent256_layer3/saved_model" \
--log_dir="check_model/nona_magneto/FFNN/case3_caseall_latent256_layer3" \
--latent_size=256 \
--output_size=27 \
--num_layer=3

