#!/bin/bash

# additional test


python3 gn_inverse_dynamics/robot_graph_generator/hexamagneto/main_make_dataset_gn.py --raw_data_dir="/a_dataset/rawData/hexa_magneto/case5_2"  \
--dataset_dir="/a_dataset/tfData/hexa_magneto/GN/case5_2" 

python3 gn_inverse_dynamics/robot_graph_generator/hexamagneto/main_make_dataset_gn.py --raw_data_dir="/a_dataset/rawData/hexa_magneto/case5_3"  \
--dataset_dir="/a_dataset/tfData/hexa_magneto/GN/case5_3" 

######################################################
#                       Training                         #
######################################################

# python3 main_train_model_ffnn.py --dataset_path="a_dataset/tfData/hexa_magneto/FFNN/case5_2"  \
# --error_model="torque" --log_dir="hexa_magneto/FFNN/case5_2_latent256_layer3" --save_model_path="/saved_model" \
# --learning_rate=1e-3 --batch_size=64 --epoch_size=300 --latent_size=256 --output_size=18 --num_layer=3

# python3 main_train_model_ffnn.py --dataset_path="a_dataset/tfData/hexa_magneto/FFNN/case5_3"  \
# --error_model="torque" --log_dir="hexa_magneto/FFNN/case5_3_latent256_layer3" --save_model_path="/saved_model" \
# --learning_rate=1e-3 --batch_size=64 --epoch_size=300 --latent_size=256 --output_size=18 --num_layer=3


#######################

# python3 main_train_model_sn.py --dataset_path="a_dataset/tfData/hexa_magneto/SN/case5_2"  \
# --error_model="torque" --log_dir="hexa_magneto/SN/case5_2_latent128_layer2_np2" --save_model_path="/saved_model" \
# --learning_rate=5e-4 --batch_size=64 --epoch_size=300 --latent_size=128 --output_size=3 --num_layer=2 --num_processing_steps=2

# python3 main_train_model_sn.py --dataset_path="a_dataset/tfData/hexa_magneto/SN/case5_3"  \
# --error_model="torque" --log_dir="hexa_magneto/SN/case5_3_latent128_layer2_np2" --save_model_path="/saved_model" \
# --learning_rate=5e-4 --batch_size=64 --epoch_size=300 --latent_size=128 --output_size=3 --num_layer=2 --num_processing_steps=2

#######################

python3 main_train_model_gn.py --dataset_path="a_dataset/tfData/hexa_magneto/GN/case5_2"  \
--error_model="torque" --log_dir="hexa_magneto/GN/case5_2_edge64_np2" --save_model_path="/saved_model" \
--learning_rate=5e-4 --batch_size=64 --epoch_size=400 --num_processing_steps=2 --edge_latent_size=64 --edge_output_size=3

python3 main_train_model_gn.py --dataset_path="a_dataset/tfData/hexa_magneto/GN/case5_3"  \
--error_model="torque" --log_dir="hexa_magneto/GN/case5_3_edge64_np2" --save_model_path="/saved_model" \
--learning_rate=5e-4 --batch_size=64 --epoch_size=400 --num_processing_steps=2 --edge_latent_size=64 --edge_output_size=3


######################################################
#                       validation                   #
######################################################


# python3 main_check_model_ffnn.py \
# --batch_size=64 \
# --dataset_path="a_dataset/tfData/hexa_magneto/FFNN/case5_2"  \
# --test_dataset_path="a_dataset/tfData/hexa_magneto/FFNN/case4" \
# --load_model_path="a_result/hexa_magneto/FFNN/case5_2_latent256_layer3/saved_model" \
# --log_dir="check_model/hexa_magneto/FFNN/case5_2_test4_latent256_layer3" \
# --latent_size=256 \
# --output_size=18 \
# --num_layer=3

# python3 main_check_model_ffnn.py \
# --batch_size=64 \
# --dataset_path="a_dataset/tfData/hexa_magneto/FFNN/case5_3"  \
# --test_dataset_path="a_dataset/tfData/hexa_magneto/FFNN/case4" \
# --load_model_path="a_result/hexa_magneto/FFNN/case5_3_latent256_layer3/saved_model" \
# --log_dir="check_model/hexa_magneto/FFNN/case5_3_test4_latent256_layer3" \
# --latent_size=256 \
# --output_size=18 \
# --num_layer=3

#######################

python3 main_check_model_gn.py \
--batch_size=64 \
--dataset_path="a_dataset/tfData/hexa_magneto/GN/case5_2"  \
--test_dataset_path="a_dataset/tfData/hexa_magneto/GN/case4" \
--load_model_path="a_result/hexa_magneto/GN/case5_2_edge64_np2/saved_model" \
--log_dir="check_model/hexa_magneto/GN/case5_2_test4_edge64_np2" \
--num_processing_steps=2 \
--edge_latent_size=64 \
--edge_output_size=3

python3 main_check_model_gn.py \
--batch_size=64 \
--dataset_path="a_dataset/tfData/hexa_magneto/GN/case5_3"  \
--test_dataset_path="a_dataset/tfData/hexa_magneto/GN/case4" \
--load_model_path="a_result/hexa_magneto/GN/case5_3_edge64_np2/saved_model" \
--log_dir="check_model/hexa_magneto/GN/case5_3_test4_edge64_np2" \
--num_processing_steps=2 \
--edge_latent_size=64 \
--edge_output_size=3

#######################

# python3 main_check_model_sn.py \
# --batch_size=64 \
# --dataset_path="a_dataset/tfData/hexa_magneto/SN/case5_2"  \
# --test_dataset_path="a_dataset/tfData/hexa_magneto/SN/case4" \
# --load_model_path="a_result/hexa_magneto/SN/case5_2_latent128_layer2_np2/saved_model" \
# --log_dir="check_model/hexa_magneto/SN/case5_2_test4_latent128_layer2_np2" \
# --latent_size=128 \
# --output_size=3 \
# --num_layer=2 \
# --num_processing_steps=2

# python3 main_check_model_sn.py \
# --batch_size=64 \
# --dataset_path="a_dataset/tfData/hexa_magneto/SN/case5_3"  \
# --test_dataset_path="a_dataset/tfData/hexa_magneto/SN/case4" \
# --load_model_path="a_result/hexa_magneto/SN/case5_3_latent128_layer2_np2/saved_model" \
# --log_dir="check_model/hexa_magneto/SN/case5_3_test4_latent128_layer2_np2" \
# --latent_size=128 \
# --output_size=3 \
# --num_layer=2 \
# --num_processing_steps=2