#!/bin/bash

# ######################################################
# #                       inclined                     #
# ######################################################
# ## c1

# ## c2
python3 gn_inverse_dynamics/main_check_model.py \
--batch_size=64 \
--dataset_path="dataset/magneto/tfData_physical_invariance/inclined_1/case2"  \
--test_dataset_path="dataset/magneto/tfData_physical_invariance/inclined_1/case2_test1" \
--load_model_path="result_data/physical_invariance/inclined_1/case2_edge64_np3/saved_model" \
--log_dir="l4dc_check_model/physical_invariance/inclined_1/case2_test1_edge64_np3" \
--num_processing_steps=3 \
--edge_latent_size=64 \
--edge_output_size=3

python3 gn_inverse_dynamics/main_check_model.py \
--batch_size=64 \
--dataset_path="dataset/magneto/tfData_physical_invariance/inclined_1/case2"  \
--test_dataset_path="dataset/magneto/tfData_physical_invariance/inclined_1/case2_test2" \
--load_model_path="result_data/physical_invariance/inclined_1/case2_edge64_np3/saved_model" \
--log_dir="l4dc_check_model/physical_invariance/inclined_1/case2_test2_edge64_np3" \
--num_processing_steps=3 \
--edge_latent_size=64 \
--edge_output_size=3


python3 gn_inverse_dynamics/main_check_model.py \
--batch_size=64 \
--dataset_path="dataset/magneto/tfData_physical_invariance/inclined_1/case2"  \
--test_dataset_path="dataset/magneto/tfData_physical_invariance/inclined_1/case2_test3" \
--load_model_path="result_data/physical_invariance/inclined_1/case2_edge64_np3/saved_model" \
--log_dir="l4dc_check_model/physical_invariance/inclined_1/case2_test3_edge64_np3" \
--num_processing_steps=3 \
--edge_latent_size=64 \
--edge_output_size=3


python3 gn_inverse_dynamics/main_check_model.py \
--batch_size=64 \
--dataset_path="dataset/magneto/tfData_physical_invariance/inclined_1/case2"  \
--test_dataset_path="dataset/magneto/tfData_physical_invariance/inclined_1/case2_test4" \
--load_model_path="result_data/physical_invariance/inclined_1/case2_edge64_np3/saved_model" \
--log_dir="l4dc_check_model/physical_invariance/inclined_1/case2_test4_edge64_np3" \
--num_processing_steps=3 \
--edge_latent_size=64 \
--edge_output_size=3

# ## c3

######################################################
#                    combination                     #
######################################################

## c1
python3 gn_inverse_dynamics/main_check_model.py \
--batch_size=64 \
--dataset_path="dataset/magneto/tfData_slope_combination/case1"  \
--test_dataset_path="dataset/magneto/tfData_slope_combination/case1_test" \
--load_model_path="result_data/slope_combination/case1_edge64_np3/saved_model" \
--log_dir="l4dc_check_model/slope_combination/case1_edge64_np3" \
--num_processing_steps=3 \
--edge_latent_size=64 \
--edge_output_size=3


## c2
python3 gn_inverse_dynamics/main_check_model.py \
--batch_size=64 \
--dataset_path="dataset/magneto/tfData_slope_combination/case2"  \
--test_dataset_path="dataset/magneto/tfData_slope_combination/case2_test" \
--load_model_path="result_data/slope_combination/case2_edge64_np3/saved_model" \
--log_dir="l4dc_check_model/slope_combination/case2_edge64_np3" \
--num_processing_steps=3 \
--edge_latent_size=64 \
--edge_output_size=3


# ## c3
python3 gn_inverse_dynamics/main_check_model.py \
--batch_size=64 \
--dataset_path="dataset/magneto/tfData_slope_combination/case3"  \
--test_dataset_path="dataset/magneto/tfData_slope_combination/case3_test" \
--load_model_path="result_data/slope_combination/case3_edge64_np3/saved_model" \
--log_dir="l4dc_check_model/slope_combination/case3_edge64_np3" \
--num_processing_steps=3 \
--edge_latent_size=64 \
--edge_output_size=3


# ## c4
python3 gn_inverse_dynamics/main_check_model.py \
--batch_size=64 \
--dataset_path="dataset/magneto/tfData_slope_combination/case4"  \
--test_dataset_path="dataset/magneto/tfData_slope_combination/case4_test" \
--load_model_path="result_data/slope_combination/case4_edge64_np3/saved_model" \
--log_dir="l4dc_check_model/slope_combination/case4_edge64_np3" \
--num_processing_steps=3 \
--edge_latent_size=64 \
--edge_output_size=3


# ## c5
python3 gn_inverse_dynamics/main_check_model.py \
--batch_size=64 \
--dataset_path="dataset/magneto/tfData_slope_combination/case5"  \
--test_dataset_path="dataset/magneto/tfData_slope_combination/case5_test" \
--load_model_path="result_data/slope_combination/case5_edge64_np3/saved_model" \
--log_dir="l4dc_check_model/slope_combination/case5_edge64_np3" \
--num_processing_steps=3 \
--edge_latent_size=64 \
--edge_output_size=3

# ## c6
python3 gn_inverse_dynamics/main_check_model.py \
--batch_size=64 \
--dataset_path="dataset/magneto/tfData_slope_combination/case6"  \
--test_dataset_path="dataset/magneto/tfData_slope_combination/case6_test" \
--load_model_path="result_data/slope_combination/case6_edge64_np3/saved_model" \
--log_dir="l4dc_check_model/slope_combination/case6_edge64_np3" \
--num_processing_steps=3 \
--edge_latent_size=64 \
--edge_output_size=3


# ## c7
python3 gn_inverse_dynamics/main_check_model.py \
--batch_size=64 \
--dataset_path="dataset/magneto/tfData_slope_combination/case7"  \
--test_dataset_path="dataset/magneto/tfData_slope_combination/case7_test" \
--load_model_path="result_data/slope_combination/case7_edge64_np3/saved_model" \
--log_dir="l4dc_check_model/slope_combination/case7_edge64_np3" \
--num_processing_steps=3 \
--edge_latent_size=64 \
--edge_output_size=3


# ## c8
python3 gn_inverse_dynamics/main_check_model.py \
--batch_size=64 \
--dataset_path="dataset/magneto/tfData_slope_combination/case8"  \
--test_dataset_path="dataset/magneto/tfData_slope_combination/case8_test" \
--load_model_path="result_data/slope_combination/case8_edge64_np3/saved_model" \
--log_dir="l4dc_check_model/slope_combination/case8_edge64_np3" \
--num_processing_steps=3 \
--edge_latent_size=64 \
--edge_output_size=3


# ######################################################
# #                       plane                        #
# ######################################################
# ## c1
python3 gn_inverse_dynamics/main_check_model.py \
--batch_size=64 \
--dataset_path="dataset/magneto/tfData_physical_invariance/plane_1/case1"  \
--test_dataset_path="dataset/magneto/tfData_physical_invariance/plane_1/case1_test" \
--load_model_path="result_data/physical_invariance/plane_1/case1_edge64_np3/saved_model" \
--log_dir="l4dc_check_model/physical_invariance/plane_1/case1_edge64_np3" \
--num_processing_steps=3 \
--edge_latent_size=64 \
--edge_output_size=3

# ## c2
python3 gn_inverse_dynamics/main_check_model.py \
--batch_size=64 \
--dataset_path="dataset/magneto/tfData_physical_invariance/plane_1/case2"  \
--test_dataset_path="dataset/magneto/tfData_physical_invariance/plane_1/case2_test" \
--load_model_path="result_data/physical_invariance/plane_1/case2_edge64_np3/saved_model" \
--log_dir="l4dc_check_model/physical_invariance/plane_1/case2_edge64_np3" \
--num_processing_steps=3 \
--edge_latent_size=64 \
--edge_output_size=3
